# Generated by Django 4.2.4 on 2023-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employs',
            name='dateofbirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employs',
            name='dateofjoining',
            field=models.DateField(),
        ),
    ]
