# Generated by Django 4.2.4 on 2023-11-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0005_remove_employs_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employs',
            name='o_id',
        ),
    ]
