# Generated by Django 4.2.4 on 2023-11-30 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0006_remove_employs_o_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_project_create',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
