# Generated by Django 4.2.4 on 2023-11-30 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0007_alter_admin_project_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employs',
            name='dateofbirth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='employs',
            name='o_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.adminhod'),
        ),
        migrations.AlterField(
            model_name='admin_project_create',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='employs',
            name='dateofjoining',
            field=models.DateField(default=None),
        ),
    ]
