# Generated by Django 4.2.4 on 2023-11-30 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0008_employs_dateofbirth_employs_o_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employs',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='employs',
            name='o_id',
        ),
        migrations.AlterField(
            model_name='admin_project_create',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employs',
            name='dateofjoining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 11, 30)),
        ),
    ]
