# Generated by Django 4.2.4 on 2023-12-01 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0010_alter_tlassigntask_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employnav',
            name='employ_options',
            field=models.BooleanField(default='1'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 1)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 1)),
        ),
    ]
