# Generated by Django 4.2.4 on 2023-12-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0011_employnav_employ_options_alter_projecttask_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employnav',
            name='projectmanager_options',
            field=models.BooleanField(default='1'),
        ),
    ]
