# Generated by Django 4.2.4 on 2023-12-04 04:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0012_employnav_projectmanager_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customholidays',
            name='companyid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicholidays',
            name='companyid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
        ),
    ]
