# Generated by Django 4.2.4 on 2023-12-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0014_checkin_companyid_checkout_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='is_employee',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='checkout',
            name='is_employee',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
