# Generated by Django 4.2.4 on 2023-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0016_company_details_companyid_companys_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='pincode',
            field=models.IntegerField(default='0'),
        ),
    ]
