# Generated by Django 4.2.4 on 2023-12-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0018_tds_companyid_alter_projecttask_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_drop',
            name='show',
            field=models.BooleanField(default=1),
        ),
    ]
