# Generated by Django 4.2.4 on 2023-12-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0019_admin_drop_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_drop',
            name='show',
            field=models.BooleanField(default=0),
        ),
    ]
