# Generated by Django 4.2.4 on 2023-12-06 04:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0021_admin_drop_parentshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='companyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 6)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 6)),
        ),
    ]
