# Generated by Django 4.2.3 on 2023-12-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0023_ac_addplans_companyregister_contact_contact1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
