# Generated by Django 4.2.3 on 2023-12-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0024_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('header2', models.CharField(max_length=100)),
                ('f1', models.CharField(max_length=100)),
                ('f2', models.CharField(max_length=100)),
                ('f3', models.CharField(max_length=100)),
                ('f4', models.CharField(default='', max_length=100)),
                ('f5', models.CharField(default='', max_length=100)),
                ('f6', models.CharField(default='', max_length=100)),
                ('f7', models.CharField(default='', max_length=100)),
                ('header3', models.CharField(max_length=100)),
                ('copyright', models.TextField()),
                ('design', models.TextField()),
            ],
            options={
                'db_table': 'Footer1',
            },
        ),
    ]
