# Generated by Django 4.2.3 on 2023-12-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0025_footer1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='navbaritem',
            table='NavbarItem',
        ),
    ]
