# Generated by Django 4.2.3 on 2023-12-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0026_alter_navbaritem_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProductivityDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_pds', models.CharField(max_length=255)),
                ('w_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'WorkProductivityDataset',
            },
        ),
        migrations.AddField(
            model_name='monitoringdetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AddField(
            model_name='screenshots',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
