# Generated by Django 4.2.3 on 2023-12-11 12:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0027_workproductivitydataset_monitoringdetails_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoringdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(default='')),
                ('discription', ckeditor.fields.RichTextField(default='')),
                ('image1', models.ImageField(default='', upload_to='images/')),
                ('image2', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='monitoring',
            name='title',
        ),
        migrations.AddField(
            model_name='monitoring',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.employs'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_log_ts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='monitoring',
            table='monitoring',
        ),
    ]
