# Generated by Django 4.2.3 on 2023-12-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0029_remove_employeeindex2_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanagement',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='image2',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='projectmanagement2',
            name='title3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectmanagement2',
            name='title4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
