# Generated by Django 4.2.3 on 2023-12-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0030_rename_image_projectmanagement_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagement',
            name='image1',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='image2',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='projectmanagement3',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
