# Generated by Django 4.2.3 on 2023-12-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0031_alter_projectmanagement_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officework1',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='officework2',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='officework4',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='screenmonitoring1',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='screenmonitoring1',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='screenmonitoring3',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
