# Generated by Django 4.2.3 on 2023-12-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0032_alter_officework1_image2_alter_officework2_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officework3',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='officework1',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
