# Generated by Django 4.2.3 on 2023-12-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0034_screenmonitoring2_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenmonitoring2',
            name='icon',
            field=models.CharField(default='', max_length=30),
        ),
    ]
