# Generated by Django 4.2.3 on 2023-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0035_alter_screenmonitoring2_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='productivity5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/')),
                ('title1', models.CharField(max_length=100)),
                ('discription1', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='productivity2',
            name='discription2',
        ),
        migrations.RemoveField(
            model_name='productivity2',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productivity2',
            name='title2',
        ),
        migrations.AlterField(
            model_name='productivity1',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productivity2',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productivity3',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productivity4',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timeattendance1',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timeattendance1',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timeattendance1',
            name='image3',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timeattendance3',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timeattendance4',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timetracking1',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timetracking1',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timetracking2',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='timetracking4',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
