# Generated by Django 4.2.3 on 2023-12-13 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0036_productivity5_remove_productivity2_discription2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employperformance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
        ),
    ]
