# Generated by Django 4.2.3 on 2023-12-15 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0037_alter_employperformance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='m_end_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_total_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='m_log_ts',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
    ]
