# Generated by Django 4.2.3 on 2023-12-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0038_monitoring_m_end_time_monitoring_m_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_project_create',
            name='companyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
    ]
