# Generated by Django 4.2.5 on 2023-12-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0040_documents_setup1_companyid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdocs',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
    ]
