# Generated by Django 4.2.5 on 2023-12-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0042_set_payroll_date_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set_payroll_date',
            name='company',
        ),
    ]
