# Generated by Django 4.2.5 on 2023-12-19 03:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0043_remove_set_payroll_date_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementsetup',
            name='companyid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AddField(
            model_name='reimbursementsetup1',
            name='companyid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 19)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 19)),
        ),
    ]
