# Generated by Django 4.2.5 on 2023-12-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0044_reimbursementsetup_companyid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halfldayvreason',
            name='companyid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
    ]
