# Generated by Django 4.2.5 on 2023-12-19 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0045_halfldayvreason_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employedata',
            name='companyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AddField(
            model_name='employedata',
            name='employ_idlength',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='task1',
            name='companyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
    ]
