# Generated by Django 4.2.5 on 2023-12-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0046_employedata_companyid_employedata_employ_idlength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='working_shifts',
            name='companyid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
    ]
