# Generated by Django 4.2.5 on 2023-12-19 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0047_working_shifts_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employlev',
            name='companyid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
    ]
