# Generated by Django 4.2.4 on 2023-12-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0049_set_payroll_date_companyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set_payroll_date',
            name='companyid',
        ),
    ]
