# Generated by Django 4.2.4 on 2023-12-20 06:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0051_set_payroll_date_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_struc',
            name='companyid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AddField(
            model_name='salary_struct',
            name='companyid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AddField(
            model_name='set_salary_structure',
            name='companyid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
    ]
