# Generated by Django 4.2.4 on 2023-12-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0052_salary_struc_companyid_salary_struct_companyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_struc',
            name='Taxable',
        ),
        migrations.RemoveField(
            model_name='salary_struc',
            name='percentageofCTC',
        ),
        migrations.RemoveField(
            model_name='salary_struc',
            name='percentageorfixed',
        ),
        migrations.AddField(
            model_name='salary_struc',
            name='select_salarycomponent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
