# Generated by Django 4.2.4 on 2023-12-20 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0053_remove_salary_struc_taxable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_shifts',
            name='ending_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='EmployeeLoginLogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=datetime.datetime(2023, 12, 20, 14, 17, 9, 863858))),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehrms.employs')),
            ],
        ),
    ]
