# Generated by Django 4.2.4 on 2023-12-21 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0055_contactinfo_footerlink_footerservice_sociallink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 57, 15, 375192)),
        ),
        migrations.AlterField(
            model_name='employperformance',
            name='employ_name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employperformance',
            name='project_name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employperformance',
            name='project_task1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
