# Generated by Django 4.2.4 on 2023-12-21 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0056_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 15, 59, 5, 912451)),
        ),
        migrations.AlterField(
            model_name='employperformance',
            name='employ_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehrms.employs'),
        ),
        migrations.AlterField(
            model_name='employperformance',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehrms.project'),
        ),
        migrations.AlterField(
            model_name='employperformance',
            name='project_task1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.projecttask'),
        ),
    ]
