# Generated by Django 4.2.4 on 2023-12-22 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0057_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='screenmon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('show1', models.BooleanField()),
                ('show2', models.BooleanField()),
                ('show3', models.BooleanField()),
                ('addon', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='admin_drop',
            name='addon',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='admin_drop',
            name='edit',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='admin_drop',
            name='show1',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='admin_drop',
            name='show2',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='admin_drop',
            name='show3',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='companys',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='companys',
            name='plantype',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='employ_drop',
            name='show1',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='employ_drop',
            name='show2',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='employ_drop',
            name='show3',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='employnav',
            name='edit',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='employnav',
            name='show1',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='employnav',
            name='show2',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='employnav',
            name='show3',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='featurestypes',
            name='show1',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='featurestypes',
            name='show2',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='featurestypes',
            name='show3',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='project_drop',
            name='show1',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='project_drop',
            name='show2',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='project_drop',
            name='show3',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 18, 32, 20, 355709)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 22)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 22)),
        ),
        migrations.CreateModel(
            name='Addonsuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(max_length=500)),
                ('addon', models.BooleanField(default=0)),
                ('companyid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys')),
            ],
        ),
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('plantype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehrms.typeofplans')),
            ],
        ),
    ]
