# Generated by Django 4.2.4 on 2023-12-22 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0059_featurestypes_parent_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurestypes',
            name='show1',
        ),
        migrations.RemoveField(
            model_name='featurestypes',
            name='show2',
        ),
        migrations.RemoveField(
            model_name='featurestypes',
            name='show3',
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 18, 42, 43, 203655)),
        ),
    ]
