# Generated by Django 4.2.4 on 2023-12-22 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0060_remove_featurestypes_show1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurestypes',
            name='show1',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='featurestypes',
            name='show2',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='featurestypes',
            name='show3',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 22, 18, 43, 32, 870626)),
        ),
    ]
