# Generated by Django 4.2.4 on 2023-12-26 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0063_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_drop',
            name='edit',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 10, 39, 48, 508802)),
        ),
    ]
