# Generated by Django 4.2.4 on 2023-12-27 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0064_project_drop_edit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='home6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('content', models.CharField(default='', max_length=900)),
                ('d1', models.CharField(default='', max_length=200)),
                ('d2', models.CharField(default='', max_length=200)),
                ('d3', models.CharField(default='', max_length=200)),
                ('d4', models.CharField(default='', max_length=200)),
                ('d5', models.CharField(default='', max_length=200)),
                ('image1', models.ImageField(default='', upload_to='images/')),
                ('content1', models.CharField(default='', max_length=900)),
                ('d6', models.CharField(default='', max_length=200)),
                ('d7', models.CharField(default='', max_length=200)),
                ('d8', models.CharField(default='', max_length=200)),
                ('d9', models.CharField(default='', max_length=200)),
                ('d10', models.CharField(default='', max_length=200)),
                ('d11', models.CharField(default='', max_length=200)),
                ('d12', models.CharField(default='', max_length=200)),
                ('image2', models.ImageField(default='', upload_to='images/')),
                ('content2', models.CharField(default='', max_length=900)),
                ('d13', models.CharField(default='', max_length=200)),
                ('d14', models.CharField(default='', max_length=200)),
                ('d15', models.CharField(default='', max_length=200)),
                ('d16', models.CharField(default='', max_length=200)),
                ('d17', models.CharField(default='', max_length=200)),
                ('d18', models.CharField(default='', max_length=200)),
                ('image3', models.ImageField(default='', upload_to='images/')),
                ('content3', models.CharField(default='', max_length=900)),
                ('d19', models.CharField(default='', max_length=200)),
                ('d20', models.CharField(default='', max_length=200)),
                ('d21', models.CharField(default='', max_length=200)),
                ('d22', models.CharField(default='', max_length=200)),
                ('d23', models.CharField(default='', max_length=200)),
                ('d24', models.CharField(default='', max_length=200)),
                ('d25', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 15, 23, 37, 199023)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 27)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2023, 12, 27)),
        ),
    ]
