# Generated by Django 4.2.4 on 2024-01-02 03:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0070_freetraillimit_alter_adminhod_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetraillimit',
            name='companyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ehrms.companys'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 9, 15, 53, 501872)),
        ),
    ]
