# Generated by Django 4.2.4 on 2024-01-02 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0071_freetraillimit_companyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetraillimit',
            name='companyid',
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 9, 45, 44, 998925)),
        ),
    ]
