# Generated by Django 4.2.4 on 2024-01-03 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0074_alter_adminhod_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companys',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 12, 39, 57, 454118)),
        ),
    ]
