# Generated by Django 4.2.4 on 2024-01-03 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0076_alter_employeeloginlogout_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonsuser',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 3)),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 13, 17, 9, 388422)),
        ),
    ]
