# Generated by Django 4.2.4 on 2024-01-03 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0077_addonsuser_date_alter_employeeloginlogout_login_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='freetraildays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freedays', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 35, 31, 651108)),
        ),
    ]
