# Generated by Django 4.2.4 on 2024-01-03 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0078_freetraildays_alter_employeeloginlogout_login_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='freetraillimit',
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 41, 20, 907752)),
        ),
    ]
