# Generated by Django 4.2.4 on 2024-01-03 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0079_delete_freetraillimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 16, 46, 32, 628390)),
        ),
        migrations.AlterField(
            model_name='freetraildays',
            name='freedays',
            field=models.IntegerField(default=15),
        ),
    ]
