# Generated by Django 4.2.4 on 2024-01-04 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0081_alter_addonsuser_date_alter_adminhod_dateofbirth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('images', models.ImageField(upload_to='images/')),
                ('content1', models.CharField(max_length=1000)),
                ('c1', models.CharField(max_length=1000)),
                ('c2', models.CharField(max_length=1000)),
                ('c3', models.CharField(max_length=1000)),
                ('images1', models.ImageField(upload_to='images/')),
                ('content2', models.CharField(max_length=1000)),
                ('images2', models.ImageField(upload_to='images/')),
                ('c4', models.CharField(max_length=1000)),
                ('c5', models.CharField(max_length=1000)),
                ('c6', models.CharField(max_length=1000)),
                ('c7', models.CharField(max_length=1000)),
                ('c8', models.CharField(max_length=1000)),
                ('c9', models.CharField(max_length=1000)),
                ('images3', models.ImageField(upload_to='images/')),
                ('images4', models.ImageField(default='', upload_to='images/')),
                ('content3', models.CharField(default='', max_length=1000)),
                ('images5', models.ImageField(default='', upload_to='images/')),
                ('content44', models.CharField(default='', max_length=250)),
                ('images6', models.ImageField(default='', upload_to='images/')),
                ('content55', models.CharField(default='', max_length=250)),
                ('images7', models.ImageField(default='', upload_to='images/')),
                ('content6', models.CharField(default='', max_length=250)),
                ('images8', models.ImageField(default='', upload_to='images/')),
                ('content7', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 9, 11, 42, 361563)),
        ),
    ]
