# Generated by Django 4.2.4 on 2024-01-04 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0083_contactinfo2_contactmessage_delete_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 43, 25, 113907)),
        ),
    ]
