# Generated by Django 4.2.4 on 2024-01-04 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0084_alter_employeeloginlogout_login_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login1',
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 56, 33, 133715)),
        ),
    ]
