# Generated by Django 4.2.4 on 2024-01-05 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0087_alter_addonsuser_date_alter_adminhod_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofplans',
            name='price_for_annual',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 17, 55, 15, 907644)),
        ),
    ]
