# Generated by Django 4.2.4 on 2024-01-10 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0091_tlassigntask_employid1_alter_addonsuser_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 17, 22, 9, 836971)),
        ),
    ]
