# Generated by Django 4.2.4 on 2024-01-11 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0093_alter_addonsuser_date_alter_adminhod_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 11, 12, 39, 437518)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
