# Generated by Django 4.2.4 on 2024-01-11 06:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0095_alter_employeeloginlogout_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 12, 22, 47, 671184)),
        ),
        migrations.AlterField(
            model_name='employperformance',
            name='project_task1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ehrms.tlassigntask'),
        ),
    ]
