# Generated by Django 4.2.4 on 2024-01-11 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0096_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 12, 44, 42, 668060)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='project_id',
            field=models.CharField(max_length=100),
        ),
    ]
