# Generated by Django 4.2.4 on 2024-01-11 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0097_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 12, 53, 34, 689123)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='project_id',
            field=models.IntegerField(),
        ),
    ]
