# Generated by Django 4.2.4 on 2024-01-11 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0099_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 14, 10, 17, 482190)),
        ),
        migrations.AlterField(
            model_name='employperformance',
            name='project_task1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
