# Generated by Django 4.2.4 on 2024-01-11 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0101_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employperformance',
            name='task_name1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 14, 22, 52, 485420)),
        ),
    ]
