# Generated by Django 5.0.1 on 2024-02-01 08:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0108_alter_addonsuser_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_project_create',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehrms.employs'),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 14, 10, 57, 13706)),
        ),
    ]
