# Generated by Django 5.0.1 on 2024-02-05 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0109_alter_admin_project_create_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonsuser',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='dateofbirth',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='dateofjoining',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='employ_payslip',
            name='dateofbirth',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 11, 56, 44, 919072)),
        ),
        migrations.AlterField(
            model_name='employs',
            name='dateofbirth',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='employs',
            name='dateofjoining',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='hr',
            name='dateofbirth',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='hr',
            name='dateofjoining',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task_date',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='task_date',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
    ]
