# Generated by Django 5.0.1 on 2024-02-05 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0110_alter_addonsuser_date_alter_adminhod_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 12, 0, 48, 489875)),
        ),
    ]
