# Generated by Django 5.0.1 on 2024-02-05 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0111_alter_employeeloginlogout_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 12, 8, 27, 9839)),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
