# Generated by Django 5.0.1 on 2024-02-05 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrms', '0112_alter_employeeloginlogout_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeloginlogout',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 14, 48, 27, 394946)),
        ),
        migrations.AlterField(
            model_name='tlassigntask',
            name='companyid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
